language: node_js
node_js:
  - "lts/erbium"
install:
  - yarn
script:
  - yarn
  # no unit test yet
before_deploy:
  - sed -i -e '/.js$/d' -e '/.css$/d' -e '/.d.ts$/d' -e '/^docs/d' .gitignore
# deploy:
#   # Deploy to https://laobubu.net/HyperMD
#   - provider: pages
#     skip-cleanup: true
#     github-token: $GITHUB_TOKEN
#     target-branch: gh-pages
#     on:
#       branch: master
#   # Publish to NPM if tagged
#   - provider: npm
#     email: "laobubu@gmail.com"
#     api_key: $NPM_TOKEN
#     skip_cleanup: true
#     on:
#       branch: master
#       tags: true
